/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as DevicesRouteImport } from './routes/devices'
import { Route as AppsRouteImport } from './routes/apps'
import { Route as IndexRouteImport } from './routes/index'
import { Route as RpcSplatRouteImport } from './routes/rpc/$'
import { Route as ApiResetRouteImport } from './routes/api/reset'
import { Route as ApiJoinRouteImport } from './routes/api/join'
import { Route as ApiControlPlaneRpcSplatRouteImport } from './routes/api/control-plane/rpc/$'

const DevicesRoute = DevicesRouteImport.update({
  id: '/devices',
  path: '/devices',
  getParentRoute: () => rootRouteImport,
} as any)
const AppsRoute = AppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const RpcSplatRoute = RpcSplatRouteImport.update({
  id: '/rpc/$',
  path: '/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiResetRoute = ApiResetRouteImport.update({
  id: '/api/reset',
  path: '/api/reset',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiJoinRoute = ApiJoinRouteImport.update({
  id: '/api/join',
  path: '/api/join',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiControlPlaneRpcSplatRoute = ApiControlPlaneRpcSplatRouteImport.update({
  id: '/api/control-plane/rpc/$',
  path: '/api/control-plane/rpc/$',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/devices': typeof DevicesRoute
  '/api/join': typeof ApiJoinRoute
  '/api/reset': typeof ApiResetRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/control-plane/rpc/$': typeof ApiControlPlaneRpcSplatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/devices': typeof DevicesRoute
  '/api/join': typeof ApiJoinRoute
  '/api/reset': typeof ApiResetRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/control-plane/rpc/$': typeof ApiControlPlaneRpcSplatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/apps': typeof AppsRoute
  '/devices': typeof DevicesRoute
  '/api/join': typeof ApiJoinRoute
  '/api/reset': typeof ApiResetRoute
  '/rpc/$': typeof RpcSplatRoute
  '/api/control-plane/rpc/$': typeof ApiControlPlaneRpcSplatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/apps'
    | '/devices'
    | '/api/join'
    | '/api/reset'
    | '/rpc/$'
    | '/api/control-plane/rpc/$'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/apps'
    | '/devices'
    | '/api/join'
    | '/api/reset'
    | '/rpc/$'
    | '/api/control-plane/rpc/$'
  id:
    | '__root__'
    | '/'
    | '/apps'
    | '/devices'
    | '/api/join'
    | '/api/reset'
    | '/rpc/$'
    | '/api/control-plane/rpc/$'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppsRoute: typeof AppsRoute
  DevicesRoute: typeof DevicesRoute
  ApiJoinRoute: typeof ApiJoinRoute
  ApiResetRoute: typeof ApiResetRoute
  RpcSplatRoute: typeof RpcSplatRoute
  ApiControlPlaneRpcSplatRoute: typeof ApiControlPlaneRpcSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/devices': {
      id: '/devices'
      path: '/devices'
      fullPath: '/devices'
      preLoaderRoute: typeof DevicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/apps': {
      id: '/apps'
      path: '/apps'
      fullPath: '/apps'
      preLoaderRoute: typeof AppsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rpc/$': {
      id: '/rpc/$'
      path: '/rpc/$'
      fullPath: '/rpc/$'
      preLoaderRoute: typeof RpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reset': {
      id: '/api/reset'
      path: '/api/reset'
      fullPath: '/api/reset'
      preLoaderRoute: typeof ApiResetRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/join': {
      id: '/api/join'
      path: '/api/join'
      fullPath: '/api/join'
      preLoaderRoute: typeof ApiJoinRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/control-plane/rpc/$': {
      id: '/api/control-plane/rpc/$'
      path: '/api/control-plane/rpc/$'
      fullPath: '/api/control-plane/rpc/$'
      preLoaderRoute: typeof ApiControlPlaneRpcSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppsRoute: AppsRoute,
  DevicesRoute: DevicesRoute,
  ApiJoinRoute: ApiJoinRoute,
  ApiResetRoute: ApiResetRoute,
  RpcSplatRoute: RpcSplatRoute,
  ApiControlPlaneRpcSplatRoute: ApiControlPlaneRpcSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
